// Thin Supabase REST/Auth data layer built on fetch (no SDK dependency).
// Reads the autogenerated project credentials. When unconfigured it returns
// empty results so the app renders premium empty states.

import { projectId, publicAnonKey } from "../../utils/supabase/info";

const URL = projectId ? `https://${projectId}.supabase.co` : "";
const ANON = publicAnonKey ?? "";

// Edge function base (Hono server). Prefix is fixed by the Make scaffold.
const FN = `${URL}/functions/v1/make-server-e8aa61da`;

export const supabaseConfigured = Boolean(projectId && publicAnonKey);

const SESSION_KEY = "tl_session";

export type Role = "super_admin" | "owner" | "staff";

export interface Session {
  access_token: string;
  refresh_token?: string;
  user: { id: string; email: string };
  role: Role;
  workspace_id: string | null;
  name?: string;
}

export function getSession(): Session | null {
  try {
    const raw = localStorage.getItem(SESSION_KEY);
    return raw ? (JSON.parse(raw) as Session) : null;
  } catch {
    return null;
  }
}

export function setSession(s: Session | null) {
  if (s) localStorage.setItem(SESSION_KEY, JSON.stringify(s));
  else localStorage.removeItem(SESSION_KEY);
}

export function currentWorkspaceId(): string | null {
  return getSession()?.workspace_id ?? null;
}

function authHeaders(): Record<string, string> {
  const s = getSession();
  return {
    apikey: ANON,
    Authorization: `Bearer ${s?.access_token ?? ANON}`,
    "Content-Type": "application/json",
  };
}

/** Refresh the access token using the stored refresh token. Returns true on success. */
async function refreshToken(): Promise<boolean> {
  const s = getSession();
  if (!s?.refresh_token) return false;
  try {
    const res = await fetch(`${URL}/auth/v1/token?grant_type=refresh_token`, {
      method: "POST",
      headers: { apikey: ANON, "Content-Type": "application/json" },
      body: JSON.stringify({ refresh_token: s.refresh_token }),
    });
    if (!res.ok) return false;
    const data = await res.json();
    setSession({
      ...s,
      access_token: data.access_token,
      refresh_token: data.refresh_token ?? s.refresh_token,
    });
    return true;
  } catch {
    return false;
  }
}

/** Fetch wrapper that transparently refreshes an expired token once, then retries. */
async function authedFetch(input: string, init: RequestInit): Promise<Response> {
  const withAuth = (): RequestInit => ({
    ...init,
    headers: { ...authHeaders(), ...(init.headers as Record<string, string>) },
  });
  let res = await fetch(input, withAuth());
  if (res.status === 401 && (await refreshToken())) {
    res = await fetch(input, withAuth());
  }
  return res;
}

/** Select rows from a table via PostgREST. Returns [] when unconfigured or on error. */
export async function select<T = Record<string, unknown>>(
  table: string,
  query = "select=*",
): Promise<T[]> {
  if (!supabaseConfigured) return [];
  try {
    const res = await authedFetch(`${URL}/rest/v1/${table}?${query}`, { method: "GET" });
    if (!res.ok) return [];
    return (await res.json()) as T[];
  } catch {
    return [];
  }
}

export async function insert<T = Record<string, unknown>>(
  table: string,
  row: Record<string, unknown>,
): Promise<T | null> {
  if (!supabaseConfigured) return null;
  try {
    const res = await authedFetch(`${URL}/rest/v1/${table}`, {
      method: "POST",
      headers: { Prefer: "return=representation" },
      body: JSON.stringify(row),
    });
    if (!res.ok) return null;
    const data = (await res.json()) as T[];
    return data[0] ?? null;
  } catch {
    return null;
  }
}

export async function update(
  table: string,
  match: string,
  patch: Record<string, unknown>,
): Promise<boolean> {
  if (!supabaseConfigured) return false;
  try {
    const res = await authedFetch(`${URL}/rest/v1/${table}?${match}`, {
      method: "PATCH",
      body: JSON.stringify(patch),
    });
    return res.ok;
  } catch {
    return false;
  }
}

/** Delete rows matching a PostgREST filter (e.g. `id=eq.<uuid>`). */
export async function del(table: string, match: string): Promise<boolean> {
  if (!supabaseConfigured) return false;
  try {
    const res = await authedFetch(`${URL}/rest/v1/${table}?${match}`, { method: "DELETE" });
    return res.ok;
  } catch {
    return false;
  }
}

interface AuthResult {
  data?: any;
  error?: string;
}

/** Password sign-in via Supabase GoTrue. */
export async function signInWithPassword(
  email: string,
  password: string,
): Promise<AuthResult> {
  if (!supabaseConfigured) {
    return { error: "Supabase is not connected yet. Connect it to enable live sign-in." };
  }
  try {
    const res = await fetch(`${URL}/auth/v1/token?grant_type=password`, {
      method: "POST",
      headers: { apikey: ANON, "Content-Type": "application/json" },
      body: JSON.stringify({ email, password }),
    });
    const data = await res.json();
    if (!res.ok) return { error: data.error_description ?? data.msg ?? "Invalid credentials" };
    return { data };
  } catch {
    return { error: "Network error reaching Supabase." };
  }
}

export async function signUp(
  email: string,
  password: string,
  meta?: Record<string, unknown>,
): Promise<AuthResult> {
  if (!supabaseConfigured) {
    return { error: "Supabase is not connected yet. Connect it to enable signup." };
  }
  try {
    const res = await fetch(`${URL}/auth/v1/signup`, {
      method: "POST",
      headers: { apikey: ANON, "Content-Type": "application/json" },
      body: JSON.stringify({ email, password, data: meta ?? {} }),
    });
    const data = await res.json();
    if (!res.ok) return { error: data.msg ?? data.error_description ?? "Signup failed" };
    return { data };
  } catch {
    return { error: "Network error reaching Supabase." };
  }
}

/** Send a password-reset email via GoTrue. */
export async function resetPassword(email: string): Promise<AuthResult> {
  if (!supabaseConfigured) {
    return { error: "Supabase is not connected yet. Connect it to enable password resets." };
  }
  try {
    const res = await fetch(`${URL}/auth/v1/recover`, {
      method: "POST",
      headers: { apikey: ANON, "Content-Type": "application/json" },
      body: JSON.stringify({ email }),
    });
    if (!res.ok) {
      const data = await res.json().catch(() => ({}));
      return { error: data.msg ?? "Could not send reset email." };
    }
    return { data: true };
  } catch {
    return { error: "Network error reaching Supabase." };
  }
}

/** Call a privileged edge-server endpoint (service-role logic lives there). */
export async function serverCall<T = any>(
  path: string,
  body?: Record<string, unknown>,
): Promise<{ data?: T; error?: string }> {
  if (!supabaseConfigured) return { error: "Supabase is not connected yet." };
  try {
    const res = await authedFetch(`${FN}${path}`, {
      method: "POST",
      body: JSON.stringify(body ?? {}),
    });
    const data = await res.json().catch(() => ({}));
    if (!res.ok) return { error: data.error ?? "Request failed." };
    return { data };
  } catch {
    return { error: "Network error reaching the server." };
  }
}

/** Initialize a Paystack checkout for a plan; returns the hosted checkout URL. */
export async function paystackInit(
  planId: string,
): Promise<{ url?: string; error?: string }> {
  const { data, error } = await serverCall<{ authorization_url: string }>(
    "/billing/paystack/init",
    { plan: planId },
  );
  if (error) return { error };
  return { url: data?.authorization_url };
}
